# Generated by Django 4.2.6 on 2023-10-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_infogroup_sub_id_alter_infogroup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogroup',
            name='website',
            field=models.CharField(default='aaa', max_length=200),
            preserve_default=False,
        ),
    ]
