# Generated by Django 4.2.6 on 2023-10-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_infogroup_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infogroup',
            old_name='website',
            new_name='site',
        ),
    ]
