# Generated by Django 4.2.6 on 2023-12-23 02:27

from django.db import migrations, models
import functools
import posix


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_infogroup_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogroup',
            name='iv',
            field=models.BinaryField(default=functools.partial(posix.urandom, *(16,), **{}), max_length=16),
        ),
    ]
