# Generated by Django 4.2.6 on 2024-02-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_infogroup_iv_remove_infogroup_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentityrelation',
            name='info_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userentityrelation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
