# Generated by Django 4.2.6 on 2024-02-06 03:44

from django.db import migrations, models
import functools
import posix


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userentityrelation_info_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infogroup',
            old_name='data',
            new_name='info_data',
        ),
        migrations.RenameField(
            model_name='infogroup',
            old_name='salt',
            new_name='info_salt',
        ),
        migrations.AddField(
            model_name='infogroup',
            name='core_data',
            field=models.BinaryField(default=None, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infogroup',
            name='core_salt',
            field=models.BinaryField(default=functools.partial(posix.urandom, *(32,), **{}), max_length=32),
        ),
    ]
