# Generated by Django 4.2.6 on 2024-02-06 13:18

from django.db import migrations, models
import functools
import posix


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_data_infogroup_info_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infogroup',
            name='core_data',
        ),
        migrations.RemoveField(
            model_name='infogroup',
            name='core_salt',
        ),
        migrations.RemoveField(
            model_name='infogroup',
            name='info_data',
        ),
        migrations.RemoveField(
            model_name='infogroup',
            name='info_salt',
        ),
        migrations.AddField(
            model_name='infogroup',
            name='extra_info',
            field=models.BinaryField(default=None, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infogroup',
            name='password',
            field=models.BinaryField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infogroup',
            name='salt',
            field=models.BinaryField(default=functools.partial(posix.urandom, *(32,), **{}), max_length=32),
        ),
        migrations.AddField(
            model_name='infogroup',
            name='site',
            field=models.BinaryField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infogroup',
            name='tags',
            field=models.BinaryField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infogroup',
            name='username',
            field=models.BinaryField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
