# Generated by Django 4.2.6 on 2024-03-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_info_id_userentityrelation_personal_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogroup',
            name='tags',
            field=models.JSONField(max_length=1024),
        ),
    ]
