# Generated by Django 4.2.6 on 2024-08-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_rename_solt_user_salt'),
        ('api', '0013_alter_infogroup_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infogroup',
            name='tags',
        ),
        migrations.AddField(
            model_name='infogroup',
            name='guid',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infogroup',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infogroup',
            name='password_nonce',
            field=models.BinaryField(default=b'', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infogroup',
            name='password_tag',
            field=models.BinaryField(default=b'', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infogroup',
            name='site_nonce',
            field=models.BinaryField(default=b'', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infogroup',
            name='site_tag',
            field=models.BinaryField(default=b'', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infogroup',
            name='username_nonce',
            field=models.BinaryField(default=b'', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infogroup',
            name='username_tag',
            field=models.BinaryField(default=b'', max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=36)),
                ('content', models.BinaryField(max_length=64)),
                ('content_nonce', models.BinaryField(max_length=64)),
                ('content_tag', models.BinaryField(max_length=64)),
                ('info_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.infogroup')),
            ],
        ),
    ]
