# Generated by Django 4.2.6 on 2024-08-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_infogroup_tags_infogroup_guid_infogroup_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infogroup',
            name='password_nonce',
        ),
        migrations.RemoveField(
            model_name='infogroup',
            name='password_tag',
        ),
        migrations.RemoveField(
            model_name='infogroup',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='infogroup',
            name='site_nonce',
        ),
        migrations.RemoveField(
            model_name='infogroup',
            name='site_tag',
        ),
        migrations.RemoveField(
            model_name='infogroup',
            name='username_nonce',
        ),
        migrations.RemoveField(
            model_name='infogroup',
            name='username_tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='content_nonce',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='content_tag',
        ),
    ]
