# Generated by Django 4.2.6 on 2024-09-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_infogroup_extra_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentityrelation',
            name='info_group',
        ),
        migrations.RemoveField(
            model_name='userentityrelation',
            name='owner',
        ),
        migrations.AddIndex(
            model_name='infogroup',
            index=models.Index(fields=['guid'], name='api_infogro_guid_6685a3_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['guid'], name='api_tag_guid_1fa97e_idx'),
        ),
        migrations.DeleteModel(
            name='UserEntityRelation',
        ),
    ]
