# Generated by Django 4.2.6 on 2023-10-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('solt', models.CharField(max_length=64)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('update_time', models.DateField(auto_now=True)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_created=True)),
                ('device', models.CharField(max_length=10)),
                ('identification', models.CharField(max_length=64)),
                ('active_time', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
