# Generated by Django 4.2.6 on 2023-10-29 08:17

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(storage=utils.storage.HashStorage(), upload_to='profile_pic'),
        ),
    ]
