# Generated by Django 4.2.6 on 2023-10-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_session_userlogintoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userlogintoken',
            name='active_time',
            field=models.DateField(default=models.DateField(auto_now_add=True)),
        ),
    ]
