# Generated by Django 4.2.6 on 2023-10-29 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_id_alter_userlogintoken_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogintoken',
            name='active_time',
            field=models.DateField(default=datetime.datetime(2023, 10, 29, 16, 34, 54, 920727)),
        ),
    ]
