# Generated by Django 4.2.6 on 2023-10-29 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_userlogintoken_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogintoken',
            name='active_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
