# Generated by Django 4.2.6 on 2023-10-31 08:38

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_user_solt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.png', storage=utils.storage.HashStorage(), upload_to='profile_pic'),
        ),
    ]
