# Generated by Django 4.2.6 on 2023-10-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1564, max_length=32),
            preserve_default=False,
        ),
    ]
