# Generated by Django 4.2.6 on 2023-10-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_user_nickname_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='08UW8vL4', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='OlxlRyAz', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='ATzVr7QL', max_length=32),
        ),
        migrations.AlterField(
            model_name='userlogintoken',
            name='device',
            field=models.CharField(default='windows', max_length=10),
        ),
        migrations.AlterField(
            model_name='userlogintoken',
            name='identification',
            field=models.CharField(default='jb7S36OHrud2GMZrASMMLUTMfkz997mSjFzb37ryxnweCBWe0Oix6a1gWxhMFZdy', max_length=64),
        ),
    ]
