# Generated by Django 4.2.6 on 2023-10-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_user_nickname_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='bD0baQck', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='4t8y0kd8', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='RvwbP7x3', max_length=32),
        ),
        migrations.AlterField(
            model_name='userlogintoken',
            name='identification',
            field=models.CharField(default='MxfDqZBJ2yJG39oT3dOSVsgiQRcMu5ezWthiIIYZ9kljcdXfw9fplNbSyxaTUq5U', max_length=64),
        ),
    ]
