# Generated by Django 4.2.6 on 2023-10-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_user_nickname_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='5iIUXw1q', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='FENwk0Za', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='aFmNmOYp', max_length=32),
        ),
        migrations.AlterField(
            model_name='userlogintoken',
            name='identification',
            field=models.CharField(default='ZkXoVbC6xh3WLqcsyMrwoHblmNcQ84pkOpQxR65kxJUASM5lGCPIA2ujU9LPDXLe', max_length=64),
        ),
    ]
