# Generated by Django 4.2.6 on 2023-10-31 12:03

from django.db import migrations, models
import functools
import utils.random


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_user_nickname_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=functools.partial(utils.random.random_string_func, *(8,), **{}), max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=functools.partial(utils.random.random_string_func, *(8,), **{}), max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=functools.partial(utils.random.random_string_func, *(8,), **{}), max_length=32),
        ),
        migrations.AlterField(
            model_name='userlogintoken',
            name='identification',
            field=models.CharField(default=functools.partial(utils.random.random_string_func, *(64,), **{}), max_length=64),
        ),
    ]
