# Generated by Django 4.2.6 on 2023-12-23 02:27

from django.db import migrations, models
import functools
import posix


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_user_nickname_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='check_code',
            field=models.CharField(default='\x10', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='iv',
            field=models.BinaryField(default=functools.partial(posix.urandom, *(16,), **{}), max_length=16),
        ),
    ]
