# Generated by Django 4.2.6 on 2023-12-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_remove_user_password_user_check_code_user_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='check_code',
            field=models.CharField(max_length=128),
        ),
    ]
