# Generated by Django 4.2.6 on 2023-12-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_alter_user_check_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='check_code',
            field=models.BinaryField(max_length=128),
        ),
    ]
