# Generated by Django 4.2.6 on 2024-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_rename_solt_user_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='check_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='iv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='guid',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='orange', max_length=32),
        ),
    ]
