# Generated by Django 4.2.6 on 2024-09-01 11:25

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_remove_user_check_code_remove_user_iv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='orange', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default.png', storage=utils.storage.HashStorage(), upload_to='profile_pic'),
        ),
    ]
