# Generated by Django 4.2.6 on 2024-09-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_alter_user_password'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['guid'], name='login_user_guid_fe959a_idx'),
        ),
    ]
